version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
      - media_volume:/home/app/web/media
      - sqlite_data:/home/app/web/db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  media_volume:
  sqlite_data: 