# Generated by Django 4.2.20 on 2025-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_enc',
            field=models.CharField(max_length=255),
        ),
    ]
