# Generated by Django 4.2.20 on 2026-03-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0002_alter_user_email_enc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hashed_password",
        ),
    ]
