# Generated by Django 4.2.20 on 2026-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0003_remove_user_hashed_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="type",
            field=models.CharField(
                choices=[
                    ("legal", "Legal"),
                    ("professional", "Professional"),
                    ("anonymous", "Anonymous"),
                    ("gaming", "Gaming"),
                    ("social", "Social"),
                    ("other", "Other"),
                    ("public", "Public"),
                    ("private", "Private"),
                    ("restricted", "Restricted"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
