# Generated by Django 4.2.20 on 2026-03-23 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "0004_persona_type_persona_username_persona_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="type",
            field=models.CharField(
                choices=[
                    ("legal", "Legal"),
                    ("professional", "Professional"),
                    ("anonymous", "Anonymous"),
                    ("gaming", "Gaming"),
                    ("social", "Social"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
