# Generated by Django 4.2.20 on 2026-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0005_alter_persona_type_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="allowed_personas",
            field=models.ManyToManyField(
                blank=True, related_name="api_tokens", to="persona.persona"
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="has_full_access",
            field=models.BooleanField(default=True),
        ),
    ]
