# Generated by Django 4.2.20 on 2025-03-31 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fundraising.fundraisingpost'),
        ),
        migrations.AddField(
            model_name='fundraisingpost',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraising_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
